### PR TITLE
Fix Bangumi API pagination by adjusting pageSize to match actual API limit

### LINKED ISSUE #2417: 搜索分类查询上限只有六百三
### 问题描述

_No response_

### 复现步骤

_No response_

### Ani 版本号

4.11.1

### 操作系统

_No response_

### 应用日志

...

### PR DESCRIPTION
**Pull request by GeneralK1ng**
## What
Adjusted the default pageSize from 30 to 20 in Repository.defaultPagingConfig to match the actual Bangumi API response limit.

## Why
The Bangumi API documentation states a maximum limit of 25 results per request, but testing revealed the actual server-side limit is 20 results. This mismatch caused:

- Inefficient pagination (requesting 25/30 but only receiving 20)
- Index calculation error
- Discarded one-third of the search results, resulting in a basic fixed number of 630

Evidence from logs:
```bash
BangumiClient: API response total=1000, data.size=20, offset=25, limit=25
```

## Where
- Change: pageSize: `30` → `20` and initialLoadSize: 20

## Related
Closes #2417

### CODE REVIEW

File: app/shared/app-data/src/commonMain/kotlin/data/repository/Repository.kt [hunk 1]
```diff
@@ -40,7 +40,8 @@ abstract class Repository(
 
     companion object {
         val defaultPagingConfig = PagingConfig(
```
Comment (Him188) [inline app/shared/app-data/src/commonMain/kotlin/data/repository/Repository.kt:42]: 这会修改全局的，建议只改 bgm 搜索的

File: app/shared/app-data/src/commonMain/kotlin/data/repository/subject/SubjectSearchRepository.kt [hunk 2]
```diff
@@ -225,6 +225,11 @@ class SubjectSearchRepository(
 
     private companion object {
         private val logger = logger<SubjectSearchRepository>()
+        private val bangumiSearchPagingConfig = PagingConfig(
+            pageSize = 20, // Bangumi API 实际最多返回 20 个结果 #2417
+            initialLoadSize = 20,
+            prefetchDistance = 20,
```
Comment (Him188) [inline app/shared/app-data/src/commonMain/kotlin/data/repository/subject/SubjectSearchRepository.kt]: prefetch 不用改，它不影响每次 fetch的大小

**Review by StageGuard — APPROVED** [review]

**Review by Him188 — APPROVED** [review]
